//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToL.ClassStats.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToLClassDate
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public System.DateTime DatePlayed { get; set; }
    }
}
