//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToL.ClassStats.PL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToLClassStatsEntities : DbContext
    {
        public ToLClassStatsEntities()
            : base("name=ToLClassStatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblToLClassDate> tblToLClassDates { get; set; }
        public virtual DbSet<tblToLClass> tblToLClasses { get; set; }
    }
}
