BEGIN
	INSERT INTO [dbo].[tblToLClasses] (Name, Faction, TimesPlayed)
	VALUES
	('Butler','Blue Dragon', 0),
	('Chronomancer', 'Blue Dragon', 0),
	('CourtWizard','Blue Dragon', 0),
	('Drunk','Blue Dragon', 0),
	('Hunter','Blue Dragon', 0),
	('Knight','Blue Dragon', 0),
	('Maid','Blue Dragon', 0),
	('Mystic','Blue Dragon', 0),
	('Noble','Blue Dragon', 0),
	('Observer','Blue Dragon', 0),
	('Paladin','Blue Dragon', 0),
	('Physician','Blue Dragon', 0),
	('Prince','Blue Dragon', 0),
	('Princess','Blue Dragon', 0),
	('Sheriff','Blue Dragon', 0),
	('Assassin','Unseen', 0),
	('Mastermind','Unseen', 0),
	('Apostle','Cult', 0),
	('CultLeader','Cult', 0),
	('Invoker','Cult', 0),
	('Ritualist','Cult', 0),
	('Seeker','Cult', 0),
	('Alchemist','Neutral', 0),
	('Fool','Neutral', 0),
	('Inquisitor','Neutral', 0),
	('Mercenary','Neutral', 0),
	('Possessor','Neutral', 0),
	('Pretender','Neutral', 0),
	('Reaper','Neutral', 0),
	('Scorned','Neutral', 0),	
	('Sellsword','Neutral', 0),
	('Sorcerer','Neutral', 0),
	('BlueDragonKing','Blue Dragon', 0),
	('UnseenKing','Unseen', 0),
	('CultKing','Cult', 0)
END